### ISSUE TITLE
Send EIP-1155 transaction type

### ISSUE THREAD

**Issue by v36372** [umbracle/ethgo#115]
Hi,

I used the example at https://github.com/umbracle/go-web3/blob/master/e2e/transaction_test.go and was successfully create a pending transaction: https://etherscan.io/tx/0x05d1ee5cef180e2b1c1313a9e310c2021c1beb9cc33b90d0c54b03b63653205a

However, it seems that the transaction has type 0, which is a legacy type, and end up being pending forever. Is there away to explicitly set the type of transaction to `0x2`, which is `EIP-1155`, or am I missing some details somewhere?

**Comment by ferranbt** [comment]
Hi! As for now, EIP-1559 transactions are not supported but it is on the near roadmap.

**Comment by ferranbt** [comment]
Initial approach in #198
