### ISSUE TITLE
how to ? go/src/github.com/umbracle/ethgo/structs_marshal_rlp.go:21:14: undefined: fastrlp.MarshalRLP

### ISSUE THREAD

**Issue by dingding001** [umbracle/ethgo#173]
![github](https://user-images.githubusercontent.com/38275674/160244242-db3afcc6-7a7a-428d-ada7-6149711b71b2.png)

**Comment by ferranbt** [comment]
Could you try with a more modern version of `go`? Yours (1.13) is from 3 years ago. I just tried the same command and it worked.

**Comment by dingding001** [comment]
go V1.18 is ok.
