### ISSUE TITLE
wallet.NewWalletFromPrivKey will get a wrong wallet address

### ISSUE THREAD

**Issue by gzzywoo** [umbracle/ethgo#174]
wallet.NewWalletFromPrivKey will get a wrong wallet address,   wallet.NewWalletFromMnemonic is correct.

**Comment by ferranbt** [comment]
Hey, could you put a Go example that reproduces this issue?

**Comment by gzzywoo** [comment]
package main

import (
	"fmt"

	"github.com/umbracle/ethgo/wallet"
)

func main() {
	// we have a key pair:
	// 9b2ce7175ab6447b606309ca3ff2abbd880dda7ea537908fdfe582df509d1e33
	// 0x3fDa7d2A80EC987d44630394CEbc91492f1230C7

	key, err := wallet.NewWalletFromPrivKey([]byte("9b2ce7175ab6447b606309ca3ff2abbd880dda7ea537908fdfe582df509d1e33"))

	if err != nil {
		panic(err)
	}
	fmt.Println("address : ", key.Address().String())
	// the output should be : 0x3fDa7d2A80EC987d44630394CEbc91492f1230C7
	// but got a wrong address :  0x940d05C745385F9bfED8AD1c542bFcFa8064464A
}

**Comment by ferranbt** [comment]
You are not converting correctly the bytes in hex `string` format to the required `[]byte`.

```
buf, _ := hex.DecodeString("9b2ce7175ab6447b606309ca3ff2abbd880dda7ea537908fdfe582df509d1e33")
key, _ := NewWalletFromPrivKey(buf)
fmt.Println(key.addr)
```
