### ISSUE TITLE
How to get pending transaction?

### ISSUE THREAD

**Issue by greyireland** [umbracle/ethgo#176]
Can implement  ethersjs on("pending",function())?

**Comment by dingding001** [comment]
data := make(chan []byte)
	_, err := Client.Subscribe("newPendingTransactions", func(b []byte) {
			data <- b
	})

**Comment by ferranbt** [comment]
Hey, as @dingding001 pointed out, you can use the `Subscribe` method for that. Unfortunately, there is no typed function for this right now.
