### ISSUE TITLE
Transaction Params (nonce, gasprice, etc)

### ISSUE THREAD

**Issue by ethermachine** [umbracle/ethgo#183]
Wondering how to define basic tx data on contract calls.

At the moment can only send the function params but failing due to low nonce (obvious)

**Comment by ferranbt** [comment]
Hi, are you talking about `abigen` generated contracts or the `contract` package?

**Comment by ethermachine** [comment]
contract

**Comment by ferranbt** [comment]
You are correct, there exists a `TxnOpts` parameter but it is not exposed at the `Txn()` level.

**Comment by ethermachine** [comment]
Thanks ! So this means I am the first person trying to send a contract transaction? Or are there alternative most efficient ways like “populate transaction” and then send a regular transaction with the arguments and on that its already possible to define nonce

**Comment by ferranbt** [comment]
I have found an extra problem, the provider for the `contract` [here](https://github.com/umbracle/ethgo/blob/master/contract/contract.go#L20) provider for the contract (which is the default one) does not populate the nonce and it should.

This `contract` object is new (one month) and it still needs a bit more cleaning to find the rough edges. Thank you for helping!

**Comment by ethermachine** [comment]
> I have found an extra problem, the provider for the `contract` [here](https://github.com/umbracle/ethgo/blob/master/contract/contract.go#L20) provider for the contract (which is the default one) does not populate the nonce and it should.
> 
> This `contract` object is new (one month) and it still needs a bit more cleaning to find the rough edges. Thank you for helping!

In the meantime, is there any alternative approach to for  example populate contract call transaction, and then send with regular tx, via signer and correct nonce? Thanks

**Comment by ferranbt** [comment]
Yes, you could do what `contract` ([here](https://github.com/umbracle/ethgo/blob/master/contract/contract.go#L43)) package does internally and fill in the nonce.

**Comment by ethermachine** [comment]
> Yes, you could do what `contract` ([here](https://github.com/umbracle/ethgo/blob/master/contract/contract.go#L43)) package does internally and fill in the nonce.

apparently my go app is importing branch 0.1.0 and the reference you mention is only available in master. How can I change it?

**Comment by ferranbt** [comment]
Indeed, that was the first change of the new release. I think I will have time to address this issue this week. I am travelling this weekend.
