### ISSUE TITLE
Why are primitive types not copied? For example gas\gasprice\nonce

### ISSUE THREAD

**Issue by greyireland** [umbracle/ethgo#219]
#169

**Comment by ferranbt** [comment]
Hey, do you mean the `Gas`, `GasPrice`, and `Nonce` fields of the `Transaction` struct?

**Comment by greyireland** [comment]
yes

**Comment by greyireland** [comment]
I miss the code `*tt = *t`,there is anther problem,this copy transaction hash is not copy

**Comment by greyireland** [comment]
I missed ,GetHash() should work
