### ISSUE TITLE
Incorrect implementation of RecoverSender

### ISSUE THREAD

**Issue by bynil** [umbracle/ethgo#238]
Current version `RecoverSender`:

https://github.com/umbracle/ethgo/blob/c54938f51df3f66047d12c51aadf641f32a68eab/wallet/signer.go#L26-L41

After EIP-2930 tx.V is 0 or 1. `v` should not be calculated this way, or it will sometimes get the wrong sender address.

How about to fix with compatibility:

```
v := new(big.Int).SetBytes(tx.V).Uint64()
if v > 1 {
	v -= 27
	if v > 1 {
		v -= e.chainID * 2
		v -= 8
	}
}
```

**Comment by ferranbt** [comment]
Thank you! I added your fix and include also more test coverage for the sign/recover workflow.
